describe('stat', () => {
    test.todo('str+1');
    test.todo('str-1');
    test.todo('str=20');
    test.todo('str<20');
    test.todo('str<=20');
    test.todo('str>20');
    test.todo('str>=20');
    test.todo('{ str: 1 }');
    test.todo('{ str: -1 }');
    test.todo('{ str: "1" }');
    test.todo('{ str: "+1" }');
    test.todo('{ str: "-1" }');
    test.todo('{ str: "=20" }');
    test.todo('{ str: "<20" }');
    test.todo('{ str: "<=20" }');
    test.todo('{ str: ">20" }');
    test.todo('{ str: ">=20" }');
    test.todo('{ str: 1, int: 1 }');
});
